define 
    # Entity
    anime sub entity,

    # Roles
    plays watched_anime,
    plays rated_anime,
    plays unrated_anime,
    plays tagged,

    # Inferred
    plays similar_to,
    plays dissimilar_to,

    # Attributes
    has anime_id,
    has title,
    has rating,
    has type,
    has episodes,
    has members;
    
    # Entity
    genre sub entity,
        # Roles
        plays tagger,
        
        # Attributes
        has name;
    
    # Entity
    user sub entity,
        # Roles
        plays anime_rater,
        plays anime_watcher,
        
        # Attributes
        has user_id,
        has user_name,
        has first_name,
        has last_name;
    
    # Relationships
    tagging sub relationship,
        relates tagged, 
        relates tagger;

    anime_watched sub relationship,
        relates watched_anime,
        relates anime_watcher;

    anime_rated sub relationship,
        relates rated_anime,
        relates anime_rater,
        has user_rating;

    anime_not_rated sub relationship,
        relates unrated_anime,
        relates anime_watcher;

    
    similar_anime sub relationship,
	    relates tagged,
        relates watched_anime,
        relates rated_anime,
	    relates similar_to;

    
    disimilar_anime sub relationship,
	    relates tagged,
        relates watched_anime,
        relates unrated_anime,
	    relates dissimilar_to;

    similar_to sub role;
    dissimilar_to sub role;
    
    # Rules
    anime_is_similar sub rule
    when {
        (tagged: $anime_a, tagger: $genre) isa tagging;
        (tagged: $anime_b, tagger: $genre) isa tagging;
    },
    then {
        (tagged: $anime_a, similar_to: $anime_b) isa similar_anime;
    };

    anime_is_not_similar sub rule
    when {
        (tagged: $anime_c, tagger: $genre_a) isa tagging;
        (tagged: $anime_d, tagger: $genre_b) isa tagging;
        $genre_a != $genre_b;
    },
    then {
        (tagged: $anime_c, dissimilar_to: $anime_d) isa disimilar_anime;
    };

    # Resources
    identifier sub attribute, datatype string;
    anime_id sub identifier;
    user_id sub identifier;
    name sub attribute, datatype string;
    user_name sub name;
    first_name sub name;
    last_name sub name;
    title sub attribute, datatype string;
    type sub attribute, datatype string;
    episodes sub attribute, datatype long;
    members sub attribute, datatype long;
    rating sub attribute, datatype double;
    user_rating sub rating;